DataArguments:
  dataset_name: ./data/aistage-mrc/train_dataset
  dataset_path: ./data/aistage-mrc
  context_path: preprocess_wiki.json
  overwrite_cache: False
  preprocessing_num_workers: null
  max_seq_length: 384
  pad_to_max_length: False
  doc_stride: 128
  max_answer_length: 30
  eval_retrieval: True
  num_clusters: 64
  top_k_retrieval: 35
  use_faiss: False
  retrieval_mode: elastic_engine
  retrieval_name: elastic_search
  sp_max_features: 50000
  sp_ngram_range: (1,2)
  tokenizer_name: klue/bert-base
  index_name: wiki-index
  stopword_path: user_dic/my_stop_dic.txt
  decompound_mode: mixed
  b: 0.75
  k1: 1.2
  es_host_address: localhost:9200
  es_similarity: bm25_similarity
  use_korean_stopwords: False
  use_korean_synonyms: False
  lowercase: False
  nori_readingform: False
  cjk_bigram: False
  decimal_digit: False
  dfr_basic_model: g
  dfr_after_effect: l
  es_normalization: h2
  dfi_measure: standardized
  ib_distribution: ll
  ib_lambda: df
  lmd_mu: 2000
  lmjm_lambda: 0.1
  rebuilt_index: False
  
ModelingArguments:
  model_name_or_path: bert-base-multilingual-cased